<a href="https://colab.research.google.com/github/wevertonmonteiro/teste-tecnico-engenharia-de-dados/blob/main/Teste_engenheiro_de_software.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Desafio Tecnico Engenharia de Dados**

In [5]:
pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.51)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2026.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26773 sha256=ea3709e5f6e9ab1532ae8a55209230777084d93578d6d777d9ced9ce05bc07e5
  Stored in directory: /root/.cache/pip/wheels/15/a1/e7/6f92f295b5272ae5c02365e6b8fa19cb93f16a537090a1cf27
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [6]:
# Importando as bibliotecas para utilizar na analise
import pandas as pd
from pandasql import sqldf

In [7]:
# Utilizo essa ferramente para executar consultas SQL nos objetos do Panda

pysqldf = lambda q: sqldf(q, globals())

In [9]:
# Carrego todos os arquivos que utilizarei na analise

buyers = pd.read_csv('/content/buyers.csv', sep=',')
order_items = pd.read_csv('/content/order_items.csv', sep=',')
orders = pd.read_csv('/content/orders.csv', sep=',')
payments = pd.read_csv('/content/payments.csv', sep=',')
products = pd.read_csv('/content/products.csv', sep=',')
sellers = pd.read_csv('/content/sellers.csv', sep=',')

In [10]:
# display(buyers.head())
# display(order_items.head())
display(orders.head())
# display(payments.head())
# display(products.head())
display(sellers.head())

   id  seller_id  buyer_id      status           created_at  total_value
0   1        114      2806   delivered  2023-08-22 05:25:59      1987.16
1   2         90      2586  processing  2024-07-19 03:57:54     24074.93
2   3         96      1849   completed  2024-06-14 22:16:15      2416.42
3   4         10       116  processing  2024-07-11 04:46:30      3871.48
4   5         16      2195   delivered  2023-09-07 20:06:40     15367.65

,id,name,state,plan,created_at
0,1,Santos & Silva Atacado Distribuidora,BA,free,2023-04-17 00:16:11
1,2,Souza & Souza Comércio Distribuidora,DF,premium,2022-09-09 22:06:21
2,3,Santos & Almeida Distribuidora Distribuidora,AM,basic,2022-12-16 08:31:25
3,4,Nascimento & Ferreira Alimentos Distribuidora,GO,basic,2023-05-30 23:12:37
4,5,Silva & Santos Suprimentos Distribuidora,BA,premium,2023-03-06 10:29:33

Desafio 1


Escreva uma query que retorne o faturamento bruto mensal dos últimos 12 meses,
considerando apenas pedidos com status 'completed' ou 'delivered'. Inclua também a
quantidade de pedidos e o ticket médio de cada mês. Ordene do mês mais recente ao mais
antigo.

In [ ]:
# Partes isoladas do DESAFIO 1
# Soma total do faturamento dos status completed' ou 'delivered’
# Somar Faturamento bruto mensal
# Somar Quantidade de pedidos
# Somar Ticket médio
# Filtrar pelos ultimos 12 meses
# Incluir quantidade de pedidos e ticket medio de cada mes
# Ordernar do mais recente ao mais antigo

PandaSQLException: (sqlite3.OperationalError) near "WHERE": syntax error
[SQL:
SELECT SUM("total_value") AS faturamento_total_bruto from orders,
WHERE "status" = "completed" OR "delivered"
LIMIT 10
]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [11]:
# Utilizo o ('%Y-%m', "created_at") para agrupar por mes
# Desafio 1
query = """
SELECT
STRFTIME('%Y-%m', "created_at") AS "mês",
SUM(total_value) AS faturamento_total_bruto,
COUNT(id) AS quantidade_pedidos,
AVG(total_value) AS ticket_medio

FROM orders

WHERE (status = 'completed' OR status = 'delivered') AND
STRFTIME('%Y-%m', "created_at") BETWEEN '2023-12' AND '2024-11'

GROUP BY STRFTIME('%Y-%m', "created_at")
ORDER BY "mês" DESC
"""

resultado_desafio1 = pysqldf(query)
resultado_desafio1

        mês  faturamento_total_bruto  quantidade_pedidos  ticket_medio
0   2024-11              56710238.63                3643  15566.906020
1   2024-10              62493439.13                3863  16177.437000
2   2024-09              60274462.50                3779  15949.844536
3   2024-08              60102539.82                3743  16057.317612
4   2024-07              59769406.95                3862  15476.283519
5   2024-06              58797774.37                3644  16135.503395
6   2024-05              60730315.72                3848  15782.306580
7   2024-04              57779312.59                3653  15816.948423
8   2024-03              61525913.64                3877  15869.464442
9   2024-02              57926376.26                3628  15966.476367
10  2024-01              59473253.15                3789  15696.292729
11  2023-12              60053131.70                3862  15549.749275

Desafio 2
A diretora comercial quer um ranking dos 10 sellers com maior crescimento de GMV entre o
trimestre atual e o anterior, mas só quer ver sellers que tiveram pelo menos 50 pedidos em ambos
os trimestres (para evitar distorção de sellers novos ou inativos).
Escreva a query que resolve esse problema, exibindo: nome do seller, estado, GMV do
trimestre anterior, GMV do trimestre atual e o percentual de crescimento. Ordene pelo maior
crescimento.

In [20]:
# Partes isoladas do DESAFIO 2
# Juntar as tabelas orders e sellers
# Somar Faturamento bruto mensal
# Somar Quantidade de pedidos
# Somar Ticket médio
# Filtrar pelos ultimos 12 meses
# Incluir quantidade de pedidos e ticket medio de cada mes
# Ordernar do mais recente ao mais antigo

query = """
SELECT
STRFTIME('%Y-%m', "created_at") AS "mês",
SUM(total_value) AS faturamento_total_bruto,
COUNT(id) AS quantidade_pedidos,
AVG(total_value) AS ticket_medio

FROM orders

WHERE (status = 'completed' OR status = 'delivered') AND
STRFTIME('%Y-%m', "created_at") BETWEEN '2023-12' AND '2024-11'

GROUP BY STRFTIME('%Y-%m', "created_at")
ORDER BY "mês" DESC
"""
resultado_desafio2 = pysqldf(query)
resultado_desafio2

        mês  faturamento_total_bruto  quantidade_pedidos  ticket_medio
0   2024-11              56710238.63                3643  15566.906020
1   2024-10              62493439.13                3863  16177.437000
2   2024-09              60274462.50                3779  15949.844536
3   2024-08              60102539.82                3743  16057.317612
4   2024-07              59769406.95                3862  15476.283519
5   2024-06              58797774.37                3644  16135.503395
6   2024-05              60730315.72                3848  15782.306580
7   2024-04              57779312.59                3653  15816.948423
8   2024-03              61525913.64                3877  15869.464442
9   2024-02              57926376.26                3628  15966.476367
10  2024-01              59473253.15                3789  15696.292729
11  2023-12              60053131.70                3862  15549.749275

In [51]:
# Desafio 2
# Exibir na seguinte ordem:
# nome do seller, CHECK
# estado, CHECK
# Criar CTE_1 com seller + GMV + quantidade no trimestre anterior - 2º trimestre (abril a junho)
# Criar CTE_2 com seller + GMV + quantidade no trimestre atual - trimestre atual é o 3º trimestre (julho a setembro)
# consulta final -> juntar as duas CTs + sellers
# e o percentual de crescimento.
# Ordene pelo maior crescimento.
# OBSERVAÇÃO: Eu interpretei “trimestre atual” como jul–set/2024 e o anterior como abr–jun/2024, pelo fato do dataset ir até novembro/2024
query = """

WITH "CTE_semestre_anterior" AS (
SELECT
seller_id,
SUM(total_value) as GMV_anterior,
COUNT(id) AS quantidade_pedidos

FROM orders

WHERE STRFTIME('%Y-%m', "created_at") BETWEEN '2024-04' AND '2024-06'

GROUP BY seller_id

HAVING COUNT(id) >= 50
),

"CTE_semestre_atual" AS (
SELECT
seller_id,
SUM(total_value) AS GMV_atual,
COUNT(id) AS quantidade_pedidos

FROM orders

WHERE STRFTIME('%Y-%m', "created_at") BETWEEN '2024-07' AND '2024-09'

GROUP BY seller_id

HAVING COUNT(id) >= 50
)

SELECT
sellers.name,
sellers.state,
ROUND(CTE_semestre_anterior.GMV_anterior, 2) AS GMV_anterior,
ROUND(CTE_semestre_atual.GMV_atual, 2) AS GMV_atual,
ROUND((CTE_semestre_atual.GMV_atual - CTE_semestre_anterior.GMV_anterior) / NULLIF(CTE_semestre_anterior.GMV_anterior, 0) * 100, 2) AS percentual_crescimento

FROM "CTE_semestre_anterior"
JOIN "CTE_semestre_atual"
ON CTE_semestre_anterior.seller_id = CTE_semestre_atual.seller_id
JOIN sellers
ON CTE_semestre_anterior.seller_id = sellers.id

ORDER BY percentual_crescimento DESC
"""

resultado_desafio2 = pysqldf(query)
resultado_desafio2

,name,state,GMV_anterior,GMV_atual,percentual_crescimento
0,Santos & Almeida Suprimentos Distribuidora,MG,998416.51,1429244.33,43.15
1,Oliveira & Santos Distribuidora Distribuidora,PA,1034970.56,1400294.04,35.30
2,Silva & Almeida Alimentos Distribuidora,RN,1028619.01,1373818.54,33.56
3,Oliveira & Ferreira Comércio Distribuidora,PA,1263296.68,1668041.05,32.04
4,Silva & Almeida Distribuidora Distribuidora,GO,1306678.35,1699323.67,30.05
5,Lima & Souza Mercado Distribuidora,MG,1007028.50,1307281.46,29.82
6,Souza & Almeida Suprimentos Distribuidora,RS,1166266.59,1496282.36,28.30
7,Silva & Santos Mercado Distribuidora,SC,1310104.40,1675973.96,27.93
8,Silva & Santos Comércio Distribuidora,DF,1151597.50,1417951.77,23.13
9,Santos & Ferreira Atacado Distribuidora,CE,4252671.39,5226412.89,22.90

Desafio 3
O time de fraudes suspeita que alguns sellers estão aplicando descontos abusivos para inflar
volume artificialmente. Você precisa encontrar todos os pedidos onde o desconto total (soma dos
descontos dos itens) representa mais de 40% do valor bruto do pedido, listando também o seller
responsável e a data do pedido. Exclua pedidos cancelados.
Escreva a query e explique brevemente o raciocínio por trás dela.

In [ ]:
# Desafio 3
query = """
SELECT *
FROM buyers
LIMIT 3
"""

resultado_desafio3 = pysqldf(query)
resultado_desafio3

,id,name,city,state,segment,created_at
0,1,Nascimento & Costa Distribuidora Mercearia,Recife,DF,supermarket,2023-04-03 03:46:36
1,2,Lima & Almeida Atacado Mercearia,Rio de Janeiro,PE,convenience,2023-08-05 01:36:12
2,3,Ferreira & Costa Grupo Mercearia,São Paulo,PR,grocery,2023-07-10 11:37:01

Desafio 4
Existe um produto com comportamento estranho: ele tem um volume de vendas alto, mas nunca
aparece como item mais vendido dentro de nenhum pedido (nunca é o item de maior valor num
pedido). Encontre todos os produtos que se encaixam nessa descrição: total de unidades vendidas
> 1.000, mas que em nenhum pedido foram o item de maior valor unitário.
Escreva a query.
Dica: window functions podem ser suas aliadas aqui e avalie os resultados e viabilidade da
análise e faça os questionamentos necessários.

In [ ]:
# Desafio 4
query = """
SELECT *
FROM buyers
LIMIT 3
"""

resultado_desafio4 = pysqldf(query)
resultado_desafio4